title: Anup Shinde
about: Adventures in software development, web applications, news, events, gossip and about the fast-changing world of technology. 
feedURL: /feed
url: http://www.anupshinde.com
defaultLayout: post