title: Anup Shinde
about: Technology blog, Tutorials, Tips, - Web development, HTML, CSS, JavaScript, Frameworks, Salesforce, Force.com, C#, How-to guides
feedURL: /feed
url: http://www.anupshinde.com
defaultLayout: post